# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2025'
email: hendrik.borgelt@tu-dortmund.de
full_name: Hendrik Borgelt
gh_action_docs_preview: true
gh_action_pypi: false
github_org: HendrikBorgelt
license: MIT
project_description: A metadata collection for catalysis related research
project_name: CatCore
project_slug: catcore

